/* AUTH */
export const AUTH_SIGNIN = 'AUTH_SIGNIN';
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS';
export const AUTH_SIGNIN_FAILURE = 'AUTH_SIGNIN_FAILURE';

export const AUTH_GET_STATUS = 'AUTH_GET_STATUS';
export const AUTH_GET_STATUS_SUCCESS = 'AUTH_GET_STATUS_SUCCESS';
export const AUTH_GET_STATUS_FAILURE = 'AUTH_GET_STATUS_FAILURE';

export const AUTH_SIGNOUT = 'AUTH_SIGNOUT';

/* POST */
export const POST_ADD = 'POST_ADD';
export const POST_ADD_SUCCESS = 'POST_ADD_SUCCESS';
export const POST_ADD_FAILURE = 'POST_ADD_FAILURE';

export const POST_GET = 'POST_GET';
export const POST_GET_SUCCESS = 'POST_GET_SUCCESS';
export const POST_GET_FAILURE = 'POST_GET_FAILURE';

export const POST_PREV_GET = 'POST_PREV_GET';
export const POST_PREV_GET_SUCCESS = 'POST_PREV_GET_SUCCESS';
export const POST_PREV_GET_FAILURE = 'POST_PREV_GET_FAILURE';

export const POST_NEXT_GET = 'POST_NEXT_GET';
export const POST_NEXT_GET_SUCCESS = 'POST_NEXT_GET_SUCCESS';
export const POST_NEXT_GET_FAILURE = 'POST_NEXT_GET_FAILURE';

export const POST_LIST = 'POST_LIST';
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS';
export const POST_LIST_FAILURE = 'POST_LIST_FAILURE';

export const POST_UPDATE = 'POST_UPDATE';
export const POST_UPDATE_SUCCESS = 'POST_UPDATE_SUCCESS';
export const POST_UPDATE_FAILURE = 'POST_UPDATE_FAILURE';

export const POST_DELETE = 'POST_DELETE';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_FAILURE = 'POST_DELETE_FAILURE';

export const POST_COUNT = 'POST_COUNT';
export const POST_COUNT_SUCCESS = 'POST_COUNT_SUCCESS';
export const POST_COUNT_FAILURE = 'POST_COUNT_FAILURE';

export const POST_RATE = 'POST_RATE';
export const POST_RATE_SUCCESS = 'POST_RATE_SUCCESS';
export const POST_RATE_FAILURE = 'POST_RATE_FAILURE';

export const POST_SEARCH = 'POST_SEARCH';
export const POST_SEARCH_SUCCESS = 'POST_SEARCH_SUCCESS';
export const POST_SEARCH_FAILURE = 'POST_SEARCH_FAILURE';

export const POST_SEARCH_COUNT = 'POST_SEARCH_COUNT';
export const POST_SEARCH_COUNT_SUCCESS = 'POST_SEARCH_COUNT_SUCCESS';
export const POST_SEARCH_COUNT_FAILURE = 'POST_SEARCH_COUNT_FAILURE';
/* CATEGORY */
export const CATEGORY_ACTIVE_CHANGE = 'CATEGORY_ACTIVE_CHANGE';

export const CATEGORY_ADD = 'CATEGORY_ADD';
export const CATEGORY_ADD_SUCCESS = 'CATEGORY_ADD_SUCCESS';
export const CATEGORY_ADD_FAILURE = 'CATEGORY_ADD_FAILURE';

export const CATEGORY_LIST = 'CATEGORY_LIST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAILURE = 'CATEGORY_LIST_FAILURE';

export const CATEGORY_UPDATE = 'CATEGORY_UPDATE';
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS';
export const CATEGORY_UPDATE_FAILURE = 'CATEGORY_UPDATE_FAILURE';

export const CATEGORY_DELETE = 'CATEGORY_DELETE';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_DELETE_FAILURE = 'CATEGORY_DELETE_FAILURE';

export const CATEGORY_GET = 'CATEGORY_GET';
export const CATEGORY_GET_SUCCESS = 'CATEGORY_GET_SUCCESS';
export const CATEGORY_GET_FAILURE = 'CATEGORY_GET_FAILURE';

/* COMMENT */
export const COMMENT_ADD = 'COMMENT_ADD';
export const COMMENT_ADD_SUCCESS = 'COMMENT_ADD_SUCCESS';
export const COMMENT_ADD_FAILURE = 'COMMENT_ADD_FAILURE';

export const COMMENT_LIST = 'COMMENT_LIST';
export const COMMENT_LIST_SUCCESS = 'COMMENT_LIST_SUCCESS';
export const COMMENT_LIST_FAILURE = 'COMMENT_LIST_FAILURE';

export const COMMENT_UPDATE = 'COMMENT_UPDATE';
export const COMMENT_UPDATE_SUCCESS = 'COMMENT_UPDATE_SUCCESS';
export const COMMENT_UPDATE_FAILURE = 'COMMENT_UPDATE_FAILURE';

export const COMMENT_DELETE = 'COMMENT_DELETE';
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS';
export const COMMENT_DELETE_FAILURE = 'COMMENT_DELETE_FAILURE';

/* ENVIRONMENT */
export const CHANGE_IS_MOBILE = 'CHANGE_IS_MOBILE';
export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';
export const NOTIFICATION_ADD = 'NOTIFICATION_ADD';
